name: bytebank
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  firebase_core: ^2.31.1
  cloud_firestore: ^4.17.3
  firebase_auth: ^4.19.6
  firebase_database: ^10.4.9

  cupertino_icons: ^1.0.8
  file_picker: ^8.0.7
  firebase_storage: ^11.7.7
  url_launcher: ^6.3.1
  flutter_pdfview: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/images/balanceCardTop.png
    - assets/images/balanceCardBottom.png
    - assets/images/porco.png
    - assets/images/cartao.png
    - assets/images/transactionCardBottom.png
    - assets/images/transactionCardTop.png

