// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaQZ8eN7n9wH25r5Wt0qEvCoHmNQDVbXU',
    appId: '1:1046846285690:web:1e2ec08e70619b818f98c3',
    messagingSenderId: '1046846285690',
    projectId: 'tech-challenge-b9efc',
    authDomain: 'tech-challenge-b9efc.firebaseapp.com',
    storageBucket: 'tech-challenge-b9efc.firebasestorage.app',
    measurementId: 'G-S153MHZ01P',
    databaseURL: 'https://tech-challenge-b9efc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDevdYlWcUlU0YLCwwm86D74TcssNqYmXY',
    appId: '1:1046846285690:android:61cf4ecd3a8919eb8f98c3',
    messagingSenderId: '1046846285690',
    projectId: 'tech-challenge-b9efc',
    storageBucket: 'tech-challenge-b9efc.firebasestorage.app',
    databaseURL: 'https://tech-challenge-b9efc-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCc-e1Cr7_0Q445g_BX91tBGS5HzJHRagg',
    appId: '1:1046846285690:ios:189c5fcf0af5eafe8f98c3',
    messagingSenderId: '1046846285690',
    projectId: 'tech-challenge-b9efc',
    storageBucket: 'tech-challenge-b9efc.firebasestorage.app',
    iosBundleId: 'com.example.bytebank',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCc-e1Cr7_0Q445g_BX91tBGS5HzJHRagg',
    appId: '1:1046846285690:ios:189c5fcf0af5eafe8f98c3',
    messagingSenderId: '1046846285690',
    projectId: 'tech-challenge-b9efc',
    storageBucket: 'tech-challenge-b9efc.firebasestorage.app',
    iosBundleId: 'com.example.bytebank',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCaQZ8eN7n9wH25r5Wt0qEvCoHmNQDVbXU',
    appId: '1:1046846285690:web:1da290e1d3e3e6878f98c3',
    messagingSenderId: '1046846285690',
    projectId: 'tech-challenge-b9efc',
    authDomain: 'tech-challenge-b9efc.firebaseapp.com',
    storageBucket: 'tech-challenge-b9efc.firebasestorage.app',
    measurementId: 'G-K6RWF9Z97T',
  );
}
